name: build2
on: [pull_request]

jobs:
  test:
#     name: test (${{ github.event_name }})
    runs-on: ubuntu-latest

    steps:
#       - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
#         run: echo "${{ toJson(github) }}"
        run: echo "Hello World!"
