name: merge_down
on:
  pull_request:
    types: [closed]

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Hello world action step
        id: hello
        uses: pearswj/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'
          token: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
