name: merge_down
on:
  pull_request:
    types: [closed]

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: mcneel/merge-down-action@v1
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.PAT }}
